k=int(input('enter 1st integer'))
j=int(input('enter 2nd integer'))
print('-----------------------')
print(f'{k} is equal to {j}',k==j)
print(f'{k} is not equal to {j}',k!=j)
print(f'{k} is greater than {j}',k>j)
print(f'{k} is greater than or equal to {j}',k>=j)
print(f'{k} is less than {j}',k<j)
print(f'{k} is less than or equal to {j}',k<=j)
print('-----------------------')
